backend:
  name: github
  repo: Camoqi/mydoC4test   # 请替换为你的 github 用户名和仓库名
  branch: main          # 或者你的默认分支

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}